[platformio]
default_envs = m5papercolor

[env:m5papercolor]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = esp32-s3-devkitc1-n16r8
board_build.mcu = esp32s3
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.flash_size = 16MB
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_unflags = -std=gnu++11
build_flags =
  -std=gnu++2a
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DEINK_DISPLAY_SINGLE_BUFFER_MODE=1
  -DFREEINK_DEVICE_M5=1
lib_deps =
  m5stack/M5Unified @ ^0.2.15
  m5stack/M5GFX @ ^0.2.21
  m5stack/M5PM1 @ ^1.0.1
  bblanchon/ArduinoJson @ ^7.4.2
  BoardConfig=symlink://third_party/freeink-sdk/libs/hardware/BoardConfig
  EInkDisplay=symlink://third_party/freeink-sdk/libs/display/FreeInkDisplay
  InputManager=symlink://third_party/freeink-sdk/libs/hardware/InputManager
  BatteryMonitor=symlink://third_party/freeink-sdk/libs/hardware/BatteryMonitor
  SDCardManager=symlink://third_party/freeink-sdk/libs/hardware/SDCardManager
  PowerManager=symlink://third_party/freeink-sdk/libs/hardware/PowerManager
  Icons=symlink://third_party/freeink-sdk/libs/assets/Icons
  FreeInkUI=symlink://third_party/freeink-sdk/libs/ui/FreeInkUI
  FreeInkBook=symlink://third_party/freeink-sdk/libs/book/FreeInkBook

